name: makeface2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  image_picker: ^0.8.4+4
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  flutter_typeahead: ^5.2.0
  shared_preferences: ^2.0.7
  string_similarity: ^2.0.0  # Add the resolved version
  url_launcher: ^6.2.6  # Keep or update this version as per your requirement

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
