name: makeface2
description: "A new Flutter project."
publish_to: 'none'  # Set to 'none' if you're not publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_signin_button: ^2.0.0
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.1.1
  audiofileplayer: ^2.1.1
  firebase_auth: ^5.1.2
  firebase_database: ^11.0.3
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.1
  provider: ^6.1.2
  shared_preferences: ^2.1.1
  permission_handler: ^11.1.0
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  story_view: ^0.16.5
  instagram_share: ^0.2.1
  camera: ^0.11.0+1
  ffmpeg_kit_flutter: ^6.0.3
  geolocator: ^12.0.0
  font_awesome_flutter: ^9.0.0
  photo_gallery: ^1.0.1
  video_player: ^2.7.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.11
  flutter_colorpicker: ^1.0.3
  firebase_storage: ^12.1.1
  cloud_firestore: ^5.1.0
  image_cropper: ^7.1.0
  image: ^4.0.14
  photo_manager: ^3.2.1

  # No new dependencies needed to be added for the view_story.dart implementation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true