name: makeface2
description: "A new Flutter project."
publish_to: 'none'  # Set to 'none' if you're not publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  image_picker: ^0.8.6+3
  flutter_typeahead: ^5.2.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.17
  string_similarity: ^2.0.0
  url_launcher: ^6.1.9
  assets_audio_player: ^3.1.1
  video_trimmer: ^3.0.1
  video_player: ^2.8.7
  instagram_share: ^0.2.1
  image_editor: ^1.5.1
  giphy_picker: ^3.0.2
  photo_view: ^0.15.0
  flutter_signature_pad: ^3.0.1
  path_provider: ^2.0.11
  ffmpeg_kit_flutter: ^6.0.3
  image: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
