name: makeface2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.7.0
  image_picker: ^0.8.6+3
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  flutter_typeahead: ^5.2.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.17
  string_similarity: ^2.0.0
  url_launcher: ^6.1.9 # This is the latest version as of my knowledge base date

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true