// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0FmRR7_3SqlhFokWKxFycqYTp8vswhPM',
    appId: '1:861805678431:web:ad2cbd40e1cd956114f0ea',
    messagingSenderId: '861805678431',
    projectId: 'makeface2-b1b26',
    authDomain: 'makeface2-b1b26.firebaseapp.com',
    storageBucket: 'makeface2-b1b26.appspot.com',
    measurementId: 'G-KWRQ65HBR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQyN__HFIFKcKR-3dhqTBPDhWFqKfIqdY',
    appId: '1:861805678431:android:611c7faf8aeb3b7514f0ea',
    messagingSenderId: '861805678431',
    projectId: 'makeface2-b1b26',
    storageBucket: 'makeface2-b1b26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBne-I78ZkxUPY6yySSgHPE5yjRikGSSC4',
    appId: '1:861805678431:ios:40a4aae30a56766914f0ea',
    messagingSenderId: '861805678431',
    projectId: 'makeface2-b1b26',
    storageBucket: 'makeface2-b1b26.appspot.com',
    iosClientId: '861805678431-dt4epqu459dgn0b8td8v4qt1kgj56ah2.apps.googleusercontent.com',
    iosBundleId: 'com.example.makeface2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBne-I78ZkxUPY6yySSgHPE5yjRikGSSC4',
    appId: '1:861805678431:ios:40a4aae30a56766914f0ea',
    messagingSenderId: '861805678431',
    projectId: 'makeface2-b1b26',
    storageBucket: 'makeface2-b1b26.appspot.com',
    iosClientId: '861805678431-dt4epqu459dgn0b8td8v4qt1kgj56ah2.apps.googleusercontent.com',
    iosBundleId: 'com.example.makeface2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0FmRR7_3SqlhFokWKxFycqYTp8vswhPM',
    appId: '1:861805678431:web:47bc68ec32fc076314f0ea',
    messagingSenderId: '861805678431',
    projectId: 'makeface2-b1b26',
    authDomain: 'makeface2-b1b26.firebaseapp.com',
    storageBucket: 'makeface2-b1b26.appspot.com',
    measurementId: 'G-QFG1PB3V28',
  );

}